SLOW_ESC=1580
MEDIUM_ESC=1600
FAST_ESC=1720
DRIVE_MEDIUM_THR=7.5
DRIVE_FAST_THR=12.5
DRIVE_FAST_ANGLE_MARGIN=60
YAW_MULTIPLIER=1.0
NUM_POINTS_BELOW_SOD3_TO_STOP=20
MODIFIER=70
MARGIN_DRIVE_SLOW=0.5
MARGIN_DRIVE_FAST=0.55
SCAN_RANGE_DELETE=170

rosrun ultimate_racer ultimate_racer_in_cpp \
    $SLOW_ESC \
    $MEDIUM_ESC \
    $FAST_ESC \
    $DRIVE_MEDIUM_THR \
    $DRIVE_FAST_THR \
    $DRIVE_FAST_ANGLE_MARGIN \
    $YAW_MULTIPLIER \
    $NUM_POINTS_BELOW_SOD3_TO_STOP \
    $MODIFIER \
    $MARGIN_DRIVE_SLOW \
    $MARGIN_DRIVE_FAST \
    $SCAN_RANGE_DELETE
